### ISSUE TITLE
npm install failing on runner

### ISSUE THREAD

**Issue by noisymime** [hyper-tuner/ini-validate-action#1]
Currently the step to install npm is failing due to a permissions error. See: https://github.com/noisymime/speeduino/actions/runs/8801391707/job/24154615049?pr=1207 

Looks like this is probably related to https://github.com/actions/runner-images/issues/9644

**Comment by karniv00l** [comment]
Fixed in: https://github.com/hyper-tuner/ini-validate-action/releases/tag/v1.0.1

Passing test PR: https://github.com/karniv00l/speeduino/pull/9
